/*
 Copyright(c) 1996-1998
 IPA, ETL, AT21, FSIABC, FXIS, InArc, MRI, NUL, SBC, Sharp, TEC, TIS

 All rights reserved.  No guarantee.
 This technology is a result of the Advanced Software  Enrichment 
 Project of Information-technology Promotion Agency, Japan (IPA).

 Permissions  to  use,  copy, modify and distribute this software
 are governed by the terms and conditions set forth in  the  file 
 COPYRIGHT, located on the top directory of this software.
 */


//----------------------------------------------------
// The following code was generated by CUP v0.9e
// Mon Feb 02 08:32:31 GMT+09:00 1998
//----------------------------------------------------

package JP.go.ipa.oz.compiler;

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SWITCH = 34;
  static final int JAVA = 40;
  static final int TIMESEQUAL = 74;
  static final int RBRACE = 47;
  static final int DEFAULT = 13;
  static final int WHILE = 39;
  static final int INT = 22;
  static final int CHAR_LITERAL = 86;
  static final int STATIC = 32;
  static final int NOTEQUAL = 71;
  static final int LBRACE = 46;
  static final int FOR = 20;
  static final int TRY = 37;
  static final int DIVIDEEQUAL = 75;
  static final int EQUAL = 67;
  static final int ONCE = 26;
  static final int FLOAT_LITERAL = 84;
  static final int CASE = 6;
  static final int CHAR = 9;
  static final int DO = 14;
  static final int DOUBLE_LITERAL = 85;
  static final int FINAL = 17;
  static final int STRING_LITERAL = 87;
  static final int TRANSIENT = 36;
  static final int MINUS = 59;
  static final int TRUE = 41;
  static final int ABSTRACT = 2;
  static final int RANGLE = 66;
  static final int IF = 21;
  static final int RETURN = 30;
  static final int RPAREN = 45;
  static final int MODEQUAL = 78;
  static final int POSTMINUSMINUS = 81;
  static final int OROREQUAL = 77;
  static final int LANGLE = 65;
  static final int POINTSTAT = 53;
  static final int DIVIDE = 63;
  static final int ANDANDEQUAL = 76;
  static final int PROTECTED = 27;
  static final int PLUSEQUAL = 72;
  static final int LONG_LITERAL = 83;
  static final int LPAREN = 44;
  static final int CELL = 8;
  static final int IDENTIFIER = 88;
  static final int INSTANTIATE = 54;
  static final int BREAK = 4;
  static final int GTE = 69;
  static final int error = 1;
  static final int QUESTION = 52;
  static final int SUPER = 33;
  static final int CATCH = 7;
  static final int FINALLY = 18;
  static final int DOT = 51;
  static final int FALSE = 42;
  static final int COMMA = 50;
  static final int MINUSEQUAL = 73;
  static final int THROW = 29;
  static final int BYTE = 5;
  static final int VOID = 38;
  static final int SHORT = 31;
  static final int TIMES = 62;
  static final int PUBLIC = 28;
  static final int INT_LITERAL = 82;
  static final int CONTINUE = 12;
  static final int CONDITION = 11;
  static final int DOUBLE = 15;
  static final int PLUS = 58;
  static final int LTE = 68;
  static final int NULL = 43;
  static final int MINUSMINUS = 61;
  static final int EQUALEQUAL = 70;
  static final int EQUALBAR = 79;
  static final int THIS = 35;
  static final int FLOAT = 19;
  static final int ANDAND = 55;
  static final int EOF = 0;
  static final int SEMI = 48;
  static final int OROR = 56;
  static final int PLUSPLUS = 60;
  static final int ELSE = 16;
  static final int POSTPLUSPLUS = 80;
  static final int NEW = 25;
  static final int CLASS = 10;
  static final int EXCLAM = 57;
  static final int COLON = 49;
  static final int LONG = 24;
  static final int MOD = 64;
  static final int LOCKED = 23;
  static final int BOOL = 3;
};

